sudo: required
services:
    - docker

before_install:
    - docker built -t atukade/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true atukade/react-test npm test

after_success:
    - docker build -t atukade/multi-client ./client
    - docker build -t atukade/multi-nginx ./nginx 
    - docker build -t atukade/multi-server ./server 
    - docker build -t atukade/multi-worker ./worker 
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to docker hub
    - docker push atukade/multi-client
    - docker push atukade/multi-nginx
    - docker push atukade/multi-server
    - docker push atukade/multi-worker